# fly.toml app configuration file generated for yells-at on 2023-12-04T22:48:58-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yells-at"
primary_region = "yul"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
