on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: deploy to fly.io
    runs-on: ubuntu-latest
    concurrency:
      group: deploy
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main 
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
        nix build .#container
        ./result | docker load
      - run: flyctl deploy --local-only --image "yells-at:latest"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
